
 CREATE OR REPLACE ALGORITHM = UNDEFINED VIEW `register_view` AS select `reg`.`index_id` AS `index_id`,`reg`.`matri_id` AS `matri_id`,`reg`.`prefix` AS `prefix`,`reg`.`email` AS `email`,`reg`.`password` AS `password`,`reg`.`cpassword` AS `cpassword`,`reg`.`cpass_status` AS `cpass_status`,`reg`.`m_status` AS `m_status`,`reg`.`profileby` AS `profileby`,`reg`.`pre_cnt_type` AS `pre_cnt_type`,`reg`.`time_to_call` AS `time_to_call`,`reg`.`reference` AS `reference`,`reg`.`username` AS `username`,`reg`.`firstname` AS `firstname`,`reg`.`lastname` AS `lastname`,`reg`.`gender` AS `gender`,`reg`.`birthdate` AS `birthdate`,`reg`.`birthtime` AS `birthtime`,`reg`.`birthplace` AS `birthplace`,`reg`.`tot_children` AS `tot_children`,`reg`.`status_children` AS `status_children`,`reg`.`income` AS `income`,`reg`.`edu_detail` AS `edu_detail`,`reg`.`occupation` AS `occupation`,`reg`.`emp_in` AS `emp_in`,`reg`.`religion` AS `religion`,`reg`.`caste` AS `caste`,`reg`.`subcaste` AS `subcaste`,`reg`.`gothra` AS `gothra`,`reg`.`star` AS `star`,`reg`.`moonsign` AS `moonsign`,`reg`.`horoscope` AS `horoscope`,`reg`.`manglik` AS `manglik`,`reg`.`m_tongue` AS `m_tongue`,`reg`.`height` AS `height`,`reg`.`weight` AS `weight`,`reg`.`b_group` AS `b_group`,`reg`.`complexion` AS `complexion`,`reg`.`bodytype` AS `bodytype`,`reg`.`diet` AS `diet`,`reg`.`smoke` AS `smoke`,`reg`.`drink` AS `drink`,`reg`.`address` AS `address`,`reg`.`country_id` AS `country_id`,`reg`.`state_id` AS `state_id`,`reg`.`city` AS `city`,`reg`.`phone` AS `phone`,`reg`.`mobile` AS `mobile`,`reg`.`contact_view_security` AS `contact_view_security`,`reg`.`residence` AS `residence`,`reg`.`father_name` AS `father_name`,`reg`.`mother_name` AS `mother_name`,`reg`.`father_living_status` AS `father_living_status`,`reg`.`mother_living_status` AS `mother_living_status`,`reg`.`father_occupation` AS `father_occupation`,`reg`.`mother_occupation` AS `mother_occupation`,`reg`.`profile_text` AS `profile_text`,`reg`.`looking_for` AS `looking_for`,`reg`.`family_details` AS `family_details`,`reg`.`family_value` AS `family_value`,`reg`.`family_type` AS `family_type`,`reg`.`family_status` AS `family_status`,`reg`.`family_origin` AS `family_origin`,`reg`.`no_of_brothers` AS `no_of_brothers`,`reg`.`no_of_sisters` AS `no_of_sisters`,`reg`.`no_marri_brother` AS `no_marri_brother`,`reg`.`no_marri_sister` AS `no_marri_sister`,`reg`.`part_frm_age` AS `part_frm_age`,`reg`.`part_to_age` AS `part_to_age`,`reg`.`part_have_child` AS `part_have_child`,`reg`.`part_income` AS `part_income`,`reg`.`part_expect` AS `part_expect`,`reg`.`part_height` AS `part_height`,`reg`.`part_height_to` AS `part_height_to`,`reg`.`part_complexation` AS `part_complexation`,`reg`.`part_resi_status` AS `part_resi_status`,`reg`.`part_country_living` AS `part_country_living`,`reg`.`part_edu` AS `part_edu`,`reg`.`part_mtongue` AS `part_mtongue`,`reg`.`part_religion` AS `part_religion`,
 `reg`.`part_caste` AS `part_caste`,
 
 
 
 `reg`.`hobby` AS `hobby`,`reg`.`hor_check` AS `hor_check`,`reg`.`hor_photo` AS `hor_photo`,`reg`.`photo_protect` AS `photo_protect`,`reg`.`photo_pswd` AS `photo_pswd`,`reg`.`video` AS `video`,`reg`.`video_approval` AS `video_approval`,`reg`.`video_url` AS `video_url`,`reg`.`photo1` AS `photo1`,`reg`.`photo1_approve` AS `photo1_approve`,`reg`.`photo2` AS `photo2`,`reg`.`photo2_approve` AS `photo2_approve`,`reg`.`photo3` AS `photo3`,`reg`.`photo3_approve` AS `photo3_approve`,`reg`.`photo4` AS `photo4`,`reg`.`photo4_approve` AS `photo4_approve`,`reg`.`photo5` AS `photo5`,`reg`.`photo5_approve` AS `photo5_approve`,`reg`.`photo6` AS `photo6`,`reg`.`photo6_approve` AS `photo6_approve`,`reg`.`reg_date` AS `reg_date`,`reg`.`ip` AS `ip`,`reg`.`agent` AS `agent`,`reg`.`last_login` AS `last_login`,`reg`.`status` AS `status`,`reg`.`fstatus` AS `fstatus`,`reg`.`logged_in` AS `logged_in`,`reg`.`adminrole_id` AS `adminrole_id`,`reg`.`adminrole_view_status` AS `adminrole_view_status`,`sta`.`state_name` AS `state_name`,`cnt`.`country_name` AS `country_name`,`rel`.`religion_name` AS `religion_name`,`cst`.`caste_name` AS `caste_name`,`ct`.`city_name` AS `city_name`,`ocp`.`ocp_name` AS `ocp_name`


 from ((((((`register` `reg` left join `caste` `cst` on((`cst`.`caste_id` = `reg`.`caste`)) 
 )left join `religion` `rel` on((`rel`.`religion_id` = `reg`.`religion`))) left join `state` `sta` on((`reg`.`state_id` = `sta`.`state_id`))) left join `country` `cnt` on((`reg`.`country_id` = `cnt`.`country_id`))) left join `city` `ct` on((`reg`.`city` = `ct`.`city_id`)))left join `occupation` `ocp` on((`reg`.`occupation` = `ocp`.`ocp_id`))) 